baseurl = "https://rdavny.com/"
title = "Ríos de Agua Viva Queens, NY"
languageCode = "en-us"
theme = "rdavny-2018"

googleAnalytics = ""

enableEmoji = true

[blackfriday]
	hrefTargetBlank	=	true


[[menu.main]]
	name	= "Home"
	url		= "/"
	weight	= -1

[[menu.main]]
	name	= "Upcoming Services"
	url		= "/events/"
	weight	= 5

[[menu.main]]
	name	= "Contact Us"
	url		= "/contact/"
	weight	= 10


[[menu.icons]]
    url		= "https://www.facebook.com/Ríos-de-Agua-Viva-Queens-NY-2010357802354332/"
    name	= "fab fa-facebook"
    weight	= 1

[[menu.icons]]
    url		= "https://goo.gl/maps/r7WoztNyoSR2"
    name	= "fas fa-map-marked-alt"
    weight	= 2
